In [1]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
print(a)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [2]:
# get 2 middle rows
middle_rows = a[1:3]
print(middle_rows)

[[5, 6, 7, 8], [9, 10, 11, 12]]


In [3]:
# get number 10
x = a[2][1]
print(x)

10


In [18]:
def print_matrix(a):
    i = 0
    while i < len(a):
        j = 0
        while j < len(a[i]):
            print('{:2}'.format(a[i][j]), end=' ')
            j += 1
        print()
        i += 1

In [10]:
a = [[1], [2, 3], [4, 5, 6], [7, 8, 9, 10]]
print(a)

[[1], [2, 3], [4, 5, 6], [7, 8, 9, 10]]


In [12]:
a = list(range(1, 10))
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
a = [list(range(1, 6)), 
     list(range(6, 11)), 
     list(range(11, 16)), 
     list(range(16, 21)), 
     list(range(21, 26))]
print(a)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [19]:
# create 5x5 list of random numbers from 0-99
import random as rd
a = [list(rd.sample(range(100), 5)),
     list(rd.sample(range(100), 5)),
     list(rd.sample(range(100), 5)),
     list(rd.sample(range(100), 5)),
     list(rd.sample(range(100), 5))]
print_matrix(a)

 2 58 74 14 21 
27 54 58 70 84 
40 37 87 97 85 
 7 82 78 38 57 
25 52  7  3 61 


In [22]:
n = int(input('Enter number n: '))
m = a[n][0] # min is the first element
i = 0
while i < len(a[n]):
    if a[n][i] < m:
        m = a[n][i]
    i += 1
print('Min:', m)

Min: 37


In [23]:
print('Min =', min(a[n]))

Min = 37


In [26]:
s = 0
i = 0
while i < len(a[n]):
    s += a[n][i]
    i += 1
print(a[n])
print('Sum =', s)
print('Sum =', sum(a[n]))

[40, 37, 87, 97, 85]
Sum = 346
Sum = 346


In [30]:
b = sorted(a[n], reverse=True)
print(a[n], b, sep='\n')

[37, 40, 85, 87, 97]
[97, 87, 85, 40, 37]


In [31]:
a[n].sort(reverse=True)
print(a[n])

[97, 87, 85, 40, 37]


In [32]:
import numpy as np

In [33]:
# create array from list
a = [1, 2, 3, 4]
b = np.array(a)
print(a, b, sep='\n')
print(type(a), type(b), sep='\n')

[1, 2, 3, 4]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [34]:
a = list(range(1, 10))
b = np.arange(1, 10)
print(a, b, sep='\n')

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [36]:
# create 10 odd numbers
a = np.arange(1, 20, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [41]:
a = np.linspace(1, 19, 10, dtype=int)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [44]:
# create 10 even numbers
a = np.linspace(2, 20, 10, dtype=int)
print(a)
a = np.arange(2, 22, 2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [45]:
print(a[3:6])

[ 8 10 12]


In [46]:
b = a // 2 # vectorized division (element by element operation)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
