In [1]:
import numpy as np

In [2]:
# list of 20 random numbers
numbers = np.random.randint(-100, 100, 20)
print(numbers)

[-85  31  17  77  25 -21  70 -31  86  -9   5  24 -83 -47  75  88 -81 -35
 -38  94]


In [4]:
# find negative numbers
i = 0
while i < len(numbers):
    if numbers[i] < 0:
        print(numbers[i], end=" ")
    i += 1

-85 -21 -31 -9 -83 -47 -81 -35 -38 

In [8]:
# boolean indexing
bool_index = numbers > 0
positives = numbers[bool_index]
print(numbers)
print(bool_index)
print(positives)

[-85  31  17  77  25 -21  70 -31  86  -9   5  24 -83 -47  75  88 -81 -35
 -38  94]
[False  True  True  True  True False  True False  True False  True  True
 False False  True  True False False False  True]
[31 17 77 25 70 86  5 24 75 88 94]


In [13]:
# find negative numbers
negatives = numbers[numbers < 0]
print(negatives)
# find odd numbers
odds = numbers[numbers % 2 == 1]
print(odds)
# find even numbers
evens = numbers[numbers % 2 == 0]
print(evens)
# find numbers that has the same digits
same_digits = numbers[numbers % 11 == 0]
print(same_digits)
same_digits = numbers[numbers // 10 == numbers % 10]
print(same_digits)
# find numbers that has the 1st digit is 8
print(numbers[np.abs(numbers) // 10 == 8])

[-85 -21 -31  -9 -83 -47 -81 -35 -38]
[-85  31  17  77  25 -21 -31  -9   5 -83 -47  75 -81 -35]
[ 70  86  24  88 -38  94]
[77 88]
[77 88]
[-85  86 -83  88 -81]


In [15]:
# array of names, array of ages
names = np.array(['John', 'Mary', 'Peter', 'Sally', 'Jane', 'Tom', 'James', 'Linda'])
ages = np.array([12, 23, 34, 45, 56, 67, 18, 89])
# find who is older than 40
olds = names[ages > 40]
print(olds)

['Sally' 'Jane' 'Tom' 'Linda']


In [17]:
# find names that starts with J
print(np.char.startswith(names, 'J'))
jnames = names[np.char.startswith(names, 'J')]
print(jnames)

[ True False False False  True False  True False]
['John' 'Jane' 'James']


In [18]:
# Fix array based on condition
print(numbers)

[-85  31  17  77  25 -21  70 -31  86  -9   5  24 -83 -47  75  88 -81 -35
 -38  94]


In [19]:
# convert negative numbers to positive numbers
numbers[numbers < 0] *= -1
print(numbers)

[85 31 17 77 25 21 70 31 86  9  5 24 83 47 75 88 81 35 38 94]


In [ ]:
# convert small numbers (less than 20) to 20
numbers[numbers < 20] = 20

In [22]:
# Create array of 10 integers from 0 to 20 (exclusive), 
# equally spacing by using linspace
numbers = np.linspace(0, 20, 10, endpoint=False, dtype=int)
print(numbers)

[ 0  2  4  6  8 10 12 14 16 18]


In [24]:
# Create array of 10 integers from 0 to 20 (exclusive), 
# equally spacing by using arange
numbers = np.arange(0, 20, 2)
print(numbers)

[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
numbers = np.random.randint(0, 100, 20)
print(numbers)

[86 91 79 42  0 37 95 65  2 79 18 52 68 76 21 41  3 67 79 68]


In [26]:
evens = numbers[numbers % 2 == 0]
odds = numbers[numbers % 2 == 1]
numbers = np.concatenate((evens, odds))
print(numbers)

[86 42  0  2 18 52 68 76 68 91 79 37 95 65 79 21 41  3 67 79]


In [27]:
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.]) 
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2]) 
v = np.zeros(6)
i = 0

while i < len(y) - 1:
    v[i] = (y[i + 1] - y[i]) / (t[i + 1] - t[i])
    i += 1

print(y, t, v, sep="\n")

[ 0.   1.3  5.  10.9 18.9 28.7 40. ]
[0.   0.49 1.   1.5  2.08 2.55 3.2 ]
[ 2.65306122  7.25490196 11.8        13.79310345 20.85106383 17.38461538]


In [28]:
v = (y[1:] - y[:-1]) / (t[1:] - t[:-1])
print(v)

[ 2.65306122  7.25490196 11.8        13.79310345 20.85106383 17.38461538]


In [29]:
# Multi-dimensional array
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
# Get number 5
print(m[1][1])
print(m[1, 1])

5
5


In [32]:
# matrix of all number 1
m = np.ones((3, 3), dtype=int)
print(m)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [33]:
# matrix of all number 10
m = m*10
print(m)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [34]:
# matrix 5x5 of random numbers
m = np.random.randint(0, 100, (5, 5))
print(m)

[[86 89 93 48 57]
 [88 97 33 74 72]
 [67 76 13  3 39]
 [72 52 81 89 63]
 [18 54 39 56 64]]


In [35]:
print(m[1:3, :3])

[[88 97 33]
 [67 76 13]]


In [36]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
m = np.array(a)
print(m)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
m = np.reshape(m, (2, 5))
print(m)
m = np.reshape(m, (5, 2))
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [39]:
a = np.array([1, 2, 3, 4, 5])
b = np.reshape(a, (5, 1))
c = np.reshape(a, (1, 5))
print(a, b, c, sep="\n")

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


In [40]:
print(np.shape(a), np.shape(b), np.shape(c), sep="\n")

(5,)
(5, 1)
(1, 5)


In [ ]:
words = {'hello':'bonjour', 'goodbye':'au revoir', 'cat':'chat', 'dog':'chien'}
w = input("Enter an English word: ")
print('French translation of {} is {}'.format(w, words[w]))

In [44]:
# add new word to words
w = input("Enter an English word: ")
f = input("Enter a French translation: ")
words[w] = f
print(words)

{'hello': 'bonjour', 'goodbye': 'au revoir', 'cat': 'chat', 'dog': 'chien', 'merci': 'thanks'}


In [45]:
# Edit a word
w = input("Enter an exist English word: ")
f = input("Enter a French translation: ")
words[w] = f
print(words)

{'hello': 'bonsoir', 'goodbye': 'au revoir', 'cat': 'chat', 'dog': 'chien', 'merci': 'thanks'}


In [48]:
# Get all the keys
print(words.keys())
print(list(words.keys()))
# Get all the values
print(list(words.values()))

dict_keys(['hello', 'goodbye', 'cat', 'dog', 'merci'])
['hello', 'goodbye', 'cat', 'dog', 'merci']
['bonsoir', 'au revoir', 'chat', 'chien', 'thanks']


In [50]:
dow = {2:'Monday', 3:'Tuesday', 4:'Wednesday', 5:'Thursday', 6:'Friday', 
       7:'Saturday', 1:'Sunday'}
day = int(input("Enter a day of week in number: "))
print('The day of week is {}'.format(dow[day]))    

The day of week is Thursday
